name: CI Index Tasks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  index-tasks:
    strategy:
      fail-fast: false
      matrix:
        index-type: ["flat", "ivfflat", "ivfpq", "hnsw"]
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            runs-on: ubuntu-latest
            docker-arch: ""
          - platform: linux/arm64
            runs-on: ubuntu-latest
            docker-arch: "--platform linux/arm64"

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4
    - name: Set cluster env
      uses: ./.github/actions/set_cluster_env
      with:
        build-type: github

    - name: Run test task for ${{ matrix.index-type }} with ${{ matrix.platform }}
      run: |
        cd test
        if [[ "${{ matrix.index-type }}" == "ivfpq" && "${{ matrix.platform }}" == "arm64" ]]; then
          pytest test_vector_index_${{ matrix.index-type }}.py -k "test_vearch_index_ivfpq_without_nsubvector or test_vearch_index_ivfpq_ip" -x --log-cli-level=INFO
        else
          pytest test_vector_index_${{ matrix.index-type }}.py -x --log-cli-level=INFO
        fi